---
  AWSTemplateFormatVersion: "2010-09-09"
  Parameters:
    dojo:
      Type: String
      Default: 'aws-workout'
    LatestAmiId:
      Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
      Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  Resources:
    S3BucketSameRegion:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: unique-name-s3-bucket-1-203
        Tags:
          - Key: "Name"
            Value: "cpu-203-s3-bucket-1"
          - Key: "Purpose"
            Value: !Ref dojo

    EC2Number1:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: 't2.micro'
        KeyName: 'aws-workout-key'
        ImageId: !Ref LatestAmiId
        NetworkInterfaces:
          - AssociatePublicIpAddress: "true"
            DeviceIndex: "0"
            GroupSet:
              - { "Fn::ImportValue": "cpu-208-security-group-id" }
            SubnetId: { "Fn::ImportValue": "net-102-subnet-1-id" }
        "UserData": {
          "Fn::Base64": {
            "Fn::Join": ["", [
              "#!/bin/bash -ex\n",
              "sudo su\n",
              "yum update -y\n",
              "yum install -y httpd\n",
              "systemctl enable httpd\n",
              "systemctl start httpd\n",
              "public_ip=$(curl 169.254.169.254/latest/meta-data/public-ipv4)\n",
              "echo \"Hello World from $(hostname -f) - PUBLIC IP: $public_ip\" > /var/www/html/index.html\n",
            ]]
          }
        }

        Tags:
          - Key: "Name"
            Value: "cpu-203-ec2-1"
          - Key: "Purpose"
            Value: !Ref dojo
