---
  AWSTemplateFormatVersion: "2010-09-09"
  Parameters:
    dojo:
      Type: String
      Default: "aws-workout"


  Resources:
    vpc101:
      Type: "AWS::EC2::VPC"
      Properties:
        CidrBlock: "10.1.0.0/16"
        Tags:
          -
            Key: "Purpose"
            Value: !Ref dojo
          -
            Key: "Name"
            Value: 'net-101-vpc'
          -
            Key: "Description"
            Value: !Sub 'A Sample VPC with a CIDR of 10.1.0.0/16 in ${AWS::Region} Region'

  Outputs:
    vpcId:
      Value: !Ref vpc101
      Export:
        Name: 'net-101-vpc-id'
