---
  AWSTemplateFormatVersion: "2010-09-09"
  Parameters:
    dojo:
      Type: String
      Default: 'aws-workout'

  Resources:
    S3BucketSameRegion:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: unique-name-s3-bucket-1-107
        Tags:
          - Key: "Name"
            Value: "net-107-s3-bucket-1"
          - Key: "Purpose"
            Value: !Ref dojo
    S3Endpoint:
      Type: 'AWS::EC2::VPCEndpoint'
      Properties:
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: '*'
              Resource: '*'
        RouteTableIds:
          - {"Fn::ImportValue" : "net-105-rt-2-id"}
        ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
        VpcId: {"Fn::ImportValue" : "net-101-vpc-id"}
