---
  AWSTemplateFormatVersion: "2010-09-09"
  Parameters:
    dojo:
      Type: String
      Default: "aws-workout"

  Resources:
    Subnet1:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId: {"Fn::ImportValue" : "net-101-vpc-id"}
        AvailabilityZone:
          Fn::Sub: "${AWS::Region}a"
        CidrBlock: "10.1.0.0/24"
        Tags:
          -
            Key: "Purpose"
            Value: !Ref dojo
          -
            Key: "Name"
            Value: 'net-102-subnet-1'
    Subnet2:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId: {"Fn::ImportValue" : "net-101-vpc-id"}
        AvailabilityZone:
          Fn::Sub: "${AWS::Region}b"
        CidrBlock: "10.1.1.0/24"
        Tags:
          -
            Key: "Purpose"
            Value: !Ref dojo
          -
            Key: "Name"
            Value: 'net-102-subnet-2'
    Subnet3:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId: {"Fn::ImportValue" : "net-101-vpc-id"}
        AvailabilityZone:
          Fn::Sub: "${AWS::Region}a"
        CidrBlock: "10.1.224.0/20"
        Tags:
          -
            Key: "Purpose"
            Value: !Ref dojo
          -
            Key: "Name"
            Value: 'net-102-subnet-3'
    Subnet4:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId: {"Fn::ImportValue" : "net-101-vpc-id"}
        AvailabilityZone:
          Fn::Sub: "${AWS::Region}b"
        CidrBlock: "10.1.240.0/20"
        Tags:
          -
            Key: "Purpose"
            Value: !Ref dojo
          -
            Key: "Name"
            Value: 'net-102-subnet-4'
  Outputs:
    subnet1Id:
      Value: !Ref Subnet1
      Export:
        Name: 'net-102-subnet-1-id'
    subnet2Id:
      Value: !Ref Subnet2
      Export:
        Name: 'net-102-subnet-2-id'
    subnet3Id:
      Value: !Ref Subnet3
      Export:
        Name: 'net-102-subnet-3-id'
    subnet4Id:
      Value: !Ref Subnet4
      Export:
        Name: 'net-102-subnet-4-id'
