---
  AWSTemplateFormatVersion: "2010-09-09"
  Parameters:
    dojo:
      Type: String
      Default: 'aws-workout'

  Resources:
    EIP:
      Type: 'AWS::EC2::EIP'
      Properties:
        Domain: vpc
        Tags:
          - Key: "Name"
            Value: "net-106-nat-gtw-eip"
          - Key: "Purpose"
            Value: !Ref dojo

    NatGateway:
      Type: 'AWS::EC2::NatGateway'
      Properties:
        AllocationId: !GetAtt 'EIP.AllocationId'
        SubnetId: {'Fn::ImportValue': 'net-102-subnet-1-id'}
        Tags:
          - Key: "Name"
            Value: "net-106-nat-gtw"
          - Key: "Purpose"
            Value: !Ref dojo

    Route:
      Type: 'AWS::EC2::Route'
      Properties:
        RouteTableId: {'Fn::ImportValue': 'net-105-rt-2-id'}
        DestinationCidrBlock: '0.0.0.0/0'
        NatGatewayId: !Ref NatGateway
    SecurityGroupRule:
      Type: AWS::EC2::SecurityGroupEgress
      Properties:
        CidrIp: '0.0.0.0/0'
        FromPort: 0
        GroupId: {'Fn::ImportValue': 'net-105-sg-2-id'}
        IpProtocol: -1
        ToPort: 0
